### ISSUE TITLE
[SHUTING] Todo

### ISSUE THREAD

**Issue by ShuTingY** [kxyoke/cs2102-fdsApp#42]
- [x] Implementation of a working cart

- [x] Implement update functionality for address, review, password card

- [x] Dropdown for customer profile link

- [x] Search bar

- [x] payment page

**Comment by ShuTingY** [comment]
DONE
