### ISSUE TITLE
[TODO: Auth] Login routes and authentication with PGSQL Express RESTFUL API.

### ISSUE THREAD

**Issue by kxyoke** [kxyoke/cs2102-fdsApp#5]
- [x] Design API for user login (and signup)
- [x] Make API for post and get request for user login info
- [ ] Add auth and auto auth (context: userIdentity)
- [x] Make login pages for each identity
- [x] Add login routes

We shall not care about any security implications for now :].

**Comment by kxyoke** [comment]
https://stackabuse.com/handling-authentication-in-express-js/

**Comment by kxyoke** [comment]
Add middleware following https://scotch.io/tutorials/build-a-restful-api-using-node-and-express-4 to check `authToken` and redirect to login page/login home if necessary.

**Comment by kxyoke** [comment]
See route handlers as middleware instead, since login pages don't require auth; instead if already authed (regardless of which login is chosen), login page should autoredirect to the original. [may change as perusal] --> This means only 1 user can be on the web app at any time.

Note that we shall implement auth as session token; if session ends, too bad.
This likely relies on context.

**Comment by kxyoke** [comment]
> https://expressjs.com/en/guide/routing.html
> See route handlers as middleware instead, since login pages don't require auth; instead if already authed (regardless of which login is chosen), login page should autoredirect to the original. [may change as perusal] --> This means only 1 user can be on the web app at any time.
> 
> Note that we shall implement auth as session token; if session ends, too bad.
> This likely relies on context.

Remember to add logout button on all screens.

**Comment by kxyoke** [comment]
See route specific middleware section https://stackoverflow.com/questions/32589927/node-express-router-route-vs-express-route

Can potentially put register auth middleware for routes branching from `/customer`, `/restaurant` etc.
