### ISSUE TITLE
KX milestones

### ISSUE THREAD

**Issue by kxyoke** [kxyoke/cs2102-fdsApp#54]
1. restaurant signups                                     [related to #43]
   - [x] add password created for restaurant [apart from `users` table, `restaurants` table now also needs the `pw hash` attribute]
   - [x] upon signup, choose to be manager (must create restaurant and its pw along with account)
   - [x] or choose to be regular staff (must choose from available restaurants and submit pw)
      - [x] similarly, `restaurantStaffs` table add a `is_manager BOOLEAN DEFAULT false`
      - [x] regardless staff or manager, still linked to their respective `res_id`s
2. orders and reviews
   - [x] implement client query to change `order` state to `is_prepared`
   - [x] implement client `foodItem` list retrieval using `[fid]` (backend implemented alr, but from postman seems like strings but be `double quoted`.)
3. add server side feedback on errors for clients to handle instead
   - [x] choose status and feedback accordingly (see others' PRs)
   - [ ] remove some client-side checks <----- **`wont fix`**
4. resolve existing issues                               [related to #53, #38, #35]
   - [x] schema issues            [#38 <----- **`wont fix`**]
   - [x] triggers to add
5. work on ui
   - [x] dashboard and summary (consider `semantic-ui-react` `feed` and `statistics`)
   - [ ] beautify other pages. <----- **`wontfix`**
6. profile
   - [x] profile: change password.
7. statistics: **for each month**
   - [x] total # completed orders
   - [x] total $ of all completed orders **excl. delivery fees**
   - [x] top 5 favs (in terms of # of orders)
8. good-to-haves
   - [ ] search for menu item (easy)

**Comment by kxyoke** [comment]
- [x] backdoor implementation of res_staffs: no auth needed to select a restaurant.
If there is no time to implement the res_manager and pws for restaurants, justify in report:
- as backdoor implementation to test the other restaurants' staff that we don't remember passwords of
- as platform for extension to managers in future, (given default pws, and managers can change it)

**Comment by kxyoke** [comment]
Current status: 1 res 1 manager.
- [ ] Only manager can edit res profile.

**Comment by kxyoke** [comment]
Current server side feedback status:
- Sends back any error with status `500`. If that happens, client alerts with the received response.

**Comment by kxyoke** [comment]
- [ ] reset daily_sells each day
- [ ] update sql functions and clients to not use food items but only use menu items. [food items merged into menu items.]

**Comment by kxyoke** [comment]
- [ ] update all profile routes [server and client] to also have the update password

**Comment by kxyoke** [comment]
Things to remove:
- updateFoodItemCategory [procedure, route, method]

**Comment by kxyoke** [comment]
> Current status: 1 res 1 manager.
> 
> * [ ]  Only manager can edit res profile.

Atm staffs can change restaurant profile as well. ^ likely **``wont fix`**.
 - Justification: staffs can change when manager is busy as well. Future extension can be manager given otp to modify or sth, who knows

**Comment by kxyoke** [comment]
Stats status:
- assuming fds day 0 = gregorian 1/1/2020
- assuming week number is 1-based

**Comment by kxyoke** [comment]
TODO:
- check the following changes work: `views.sql`, `restaurantQuery.sql`, `restaurant.js`
- when implementing dashboard, check `utils.js#getDate` functions
- actually check that merges dont break the program

**Comment by kxyoke** [comment]
- [ ] confirm that there is/isn't trigger on orders to create entry in deliveries on insert

**Comment by kxyoke** [comment]
Fix:
- [ ] Orders: load incomplete before even touching the page (now only loads when clicked on tab)
- [ ] Orders: check prepared shown correctly and updates when clicked and disappears appropriately
- [ ] Init
- [ ] Customers menu help

**Comment by kxyoke** [comment]
DEMO: will use User `Kadeem` with pw `78969`
In `init.sql`:
- [ ] Add completed deliveries (hence orders) for `Kadeem`
- [ ]
